// <auto-generated />
using System;
using Automatica.Core.HyperSeries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automatica.Core.HyperSeries.Migrations
{
    [DbContext(typeof(HyperSeriesContext))]
    [Migration("20230821115102_AddViews")]
    partial class AddViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automatica.Core.HyperSeries.Model.AggregatedRecordValue", b =>
                {
                    b.Property<double>("AverageValue")
                        .HasColumnType("double precision")
                        .HasColumnName("avgValue");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<double>("DifferenceValue")
                        .HasColumnType("double precision")
                        .HasColumnName("diffValue");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("maxValue");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("minValue");

                    b.Property<Guid>("NodeInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("nodeInstanceId");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.ToTable("AggregatedRecordValues");
                });

            modelBuilder.Entity("Automatica.Core.HyperSeries.Model.RecordValue", b =>
                {
                    b.Property<Guid>("NodeInstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TrendId")
                        .HasColumnType("uuid");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.ToTable("RecordValues");
                });
#pragma warning restore 612, 618
        }
    }
}
