trigger:
  - master  
  - develop
  
pool:
  vmImage: ubuntu-latest

variables:
  - group: automatica.core variables

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(SDK_VERSION)'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests.csproj'
    arguments: '--configuration $(BuildConfiguration) -l trx  /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"'

- task: AutomaticaCoreDockerMultiArchCli@8
  displayName: Docker multi-arch
  inputs:
    dockerRegistryEndpoint: 'DockerHub'
    dockerfile_amd64: 'Dockerfile'
    dockerfile_arm32: 'Dockerfile.arm32'
    imageName: 'automaticacore/automatica.supervisor'
    buildArgs: |
      VERSION=$(AUTOMATICA_VERSION).$(Build.BuildId)
      DEFAULT_IMAGE=automaticacore/automatica
      DOCKER_REGISTRY=https://registry.hub.docker.com
    version: '$(AUTOMATICA_VERSION).$(Build.BuildId)'

  