version: '3'
 
services:
  automatica:
    image: automaticacore/automatica-demo:latest-develop
    ports:
      - "5001:5001"
 
  nginx:
    image: automaticacore/automaticacore_proxy:develop-latest
    restart: always
    ports:
      - "80:80"
    links:
      - automatica
      
  timescale_automatica:
    image: timescale/timescaledb:latest-pg15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    links:
      - automatica
      
      
      