export const navigation = [
    {
        text: "Home",
        path: "home",
        icon: "home",
        default: true
    }, {
        text: "COMMON.CONFIGURATION",
        path: "config",
        icon: "cogs"
    }, {
        text: "COMMON.RULEENGINE",
        path: "logic-editor",
        icon: "play"
    }, {
        text: "COMMON.VISU",
        path: "visualisation",
        icon: "eye"
    }, {
        text: "COMMON.AREAS",
        path: "area-config",
        icon: "list"
    }, {
        text: "COMMON.CATEGORIES",
        path: "category-config",
        icon: "stream"
    }, {
        text: "PERMISSION.USERS",
        path: "user-config",
        icon: "user"
    }, {
        text: "PERMISSION.GROUPS",
        path: "usergroup-config",
        icon: "users"
    }, {
        text: "COMMON.TELEGRAM_MONITOR",
        path: "telegram-monitor",
        icon: "tv"
    }, {
        text: "COMMON.LICENSE",
        path: "license",
        icon: "folder"
    }, {
        text: "COMMON.SYSTEM",
        path: "system",
        icon: "folder"
    }, {
        text: "COMMON.PLUGINS",
        path: "plugins",
        icon: "folder"
    }];
