trigger:
  - master  
  - develop
  
pool:
  vmImage: ubuntu-latest

variables:
  - group: automatica.core variables

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(SDK_VERSION)'

- task: Bash@3
  displayName:  Install tools
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install automatica-cli  --global  2>/dev/null
      dotnet tool update automatica-cli -g  2>/dev/null

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    
    nugetConfigPath: 'NuGet.Config'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests.csproj'
    arguments: '--configuration $(BuildConfiguration) -l trx  /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"'

- task: AutomaticaCoreDockerMultiArchCli@7
  displayName: Docker multi-arch
  inputs:
    dockerRegistryEndpoint: 'DockerHub'
    dockerfile_amd64: 'Dockerfile'
    dockerfile_arm32: 'Dockerfile.arm32'
    imageName: 'automaticacore/automatica.satellite'
    buildArgs: |
      VERSION=$(AUTOMATICA_VERSION).$(Build.BuildId)
      CONFIG=$(BuildConfiguration)
    version: '$(AUTOMATICA_VERSION).$(Build.BuildId)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
  