// <auto-generated />
using System;
using Automatica.Core.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Automatica.Core.EF.Migrations
{
    [DbContext(typeof(AutomaticaContext))]
    [Migration("20181228090951_AddedIsReadonlyToSettings")]
    partial class AddedIsReadonlyToSettings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Automatica.Core.EF.Models.Areas.AreaInstance", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsFavorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Rating");

                    b.Property<Guid>("This2AreaTemplate");

                    b.Property<Guid?>("This2Parent");

                    b.Property<Guid?>("This2UserGroup");

                    b.HasKey("ObjId");

                    b.HasIndex("This2AreaTemplate");

                    b.HasIndex("This2Parent");

                    b.HasIndex("This2UserGroup");

                    b.ToTable("AreaInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Areas.AreaTemplate", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsDeleteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("NeedsThis2AreaType");

                    b.Property<Guid>("ProvidesThis2AreayType");

                    b.Property<Guid>("This2AreaType");

                    b.HasKey("ObjId");

                    b.HasIndex("NeedsThis2AreaType");

                    b.HasIndex("ProvidesThis2AreayType");

                    b.HasIndex("This2AreaType");

                    b.ToTable("AreaTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Areas.AreaType", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("AreaTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.BoardInterface", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("This2BoardType");

                    b.Property<Guid>("This2InterfaceType");

                    b.HasKey("ObjId");

                    b.HasIndex("This2BoardType");

                    b.HasIndex("This2InterfaceType");

                    b.ToTable("BoardInterfaces");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.BoardType", b =>
                {
                    b.Property<Guid>("Type");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Type");

                    b.ToTable("BoardTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Categories.CategoryGroup", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("CategoryGroups");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Categories.CategoryInstance", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasDefaultValue("rgba(255, 255, 255, 1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<bool>("IsDeleteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Rating");

                    b.Property<Guid>("This2CategoryGroup");

                    b.Property<Guid?>("This2UserGroup");

                    b.HasKey("ObjId");

                    b.HasIndex("This2CategoryGroup");

                    b.HasIndex("This2UserGroup");

                    b.ToTable("CategoryInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.InterfaceType", b =>
                {
                    b.Property<Guid>("Type");

                    b.Property<bool>("CanProvideBoardType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsDriverInterface")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("MaxChilds")
                        .HasColumnType("int(11)");

                    b.Property<int>("MaxInstances")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Type");

                    b.ToTable("InterfaceTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Link", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid?>("This2NodeInstance2RulePageInput");

                    b.Property<Guid?>("This2NodeInstance2RulePageOutput");

                    b.Property<Guid?>("This2RuleInterfaceInstanceInput");

                    b.Property<Guid?>("This2RuleInterfaceInstanceOutput");

                    b.Property<Guid>("This2RulePage");

                    b.HasKey("ObjId");

                    b.HasIndex("This2NodeInstance2RulePageInput");

                    b.HasIndex("This2NodeInstance2RulePageOutput");

                    b.HasIndex("This2RuleInterfaceInstanceInput");

                    b.HasIndex("This2RuleInterfaceInstanceOutput");

                    b.HasIndex("This2RulePage");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeDataType", b =>
                {
                    b.Property<long>("Type")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Type");

                    b.ToTable("NodeDataTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeInstance", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFavorite");

                    b.Property<bool>("IsReadable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWriteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Rating");

                    b.Property<string>("StateColorValueFalse")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("rgba(0, 0, 0, 1)");

                    b.Property<string>("StateColorValueTrue")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("rgba(0, 0, 0, 1)");

                    b.Property<string>("StateTextValueFalse")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("0");

                    b.Property<string>("StateTextValueTrue")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("1");

                    b.Property<Guid?>("This2AreaInstance");

                    b.Property<Guid?>("This2CategoryInstance");

                    b.Property<Guid?>("This2NodeTemplate");

                    b.Property<Guid?>("This2ParentNodeInstance");

                    b.Property<Guid?>("This2UserGroup");

                    b.Property<bool>("UseInVisu")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("VisuName");

                    b.HasKey("ObjId");

                    b.HasIndex("This2AreaInstance");

                    b.HasIndex("This2CategoryInstance");

                    b.HasIndex("This2NodeTemplate");

                    b.HasIndex("This2ParentNodeInstance");

                    b.HasIndex("This2UserGroup");

                    b.ToTable("NodeInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeInstance2RulePage", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("This2NodeInstance");

                    b.Property<Guid>("This2RulePage");

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.HasKey("ObjId");

                    b.HasIndex("This2NodeInstance");

                    b.HasIndex("This2RulePage");

                    b.ToTable("NodeInstance2RulePages");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeTemplate", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("DefaultCreated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool?>("IsAdapterInterface")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReadable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsReadableFixed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWriteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsWriteableFixed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("MaxInstances")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("NameMeta")
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("NeedsInterface2InterfacesType");

                    b.Property<Guid>("ProvidesInterface2InterfaceType");

                    b.Property<Guid>("This2DefaultMobileVisuTemplate")
                        .HasDefaultValue(new Guid("16780dfd-887a-4a0a-9b2a-4d62ccc32c93"));

                    b.Property<long>("This2NodeDataType")
                        .HasColumnType("bigint(20)");

                    b.HasKey("ObjId");

                    b.HasIndex("NeedsInterface2InterfacesType");

                    b.HasIndex("ProvidesInterface2InterfaceType");

                    b.HasIndex("This2DefaultMobileVisuTemplate");

                    b.HasIndex("This2NodeDataType");

                    b.ToTable("NodeTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Plugin", b =>
                {
                    b.Property<Guid?>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AzureFileName");

                    b.Property<string>("AzureUrl");

                    b.Property<string>("ComponentName");

                    b.Property<bool?>("IsPrerelease");

                    b.Property<bool?>("IsPublic");

                    b.Property<bool>("Loaded");

                    b.Property<string>("MinCoreServerVersion");

                    b.Property<string>("Name");

                    b.Property<Guid?>("PluginGuid");

                    b.Property<int>("PluginType");

                    b.Property<string>("Publisher");

                    b.Property<string>("Version");

                    b.HasKey("ObjId");

                    b.ToTable("Plugins");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyInstance", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid?>("This2NodeInstance");

                    b.Property<Guid>("This2PropertyTemplate");

                    b.Property<Guid?>("This2VisuObjectInstance");

                    b.Property<Guid?>("ValueAreaInstance");

                    b.Property<bool?>("ValueBool")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ValueCategoryInstance");

                    b.Property<double?>("ValueDouble");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int(11)");

                    b.Property<long?>("ValueLong")
                        .HasColumnType("bigint(64)");

                    b.Property<Guid?>("ValueNodeInstance");

                    b.Property<Guid?>("ValueRulePage");

                    b.Property<string>("ValueString")
                        .HasColumnType("text");

                    b.Property<Guid?>("ValueVisuPage");

                    b.HasKey("ObjId");

                    b.HasIndex("This2NodeInstance");

                    b.HasIndex("This2PropertyTemplate");

                    b.HasIndex("This2VisuObjectInstance");

                    b.HasIndex("ValueAreaInstance");

                    b.HasIndex("ValueCategoryInstance");

                    b.HasIndex("ValueNodeInstance");

                    b.HasIndex("ValueRulePage");

                    b.HasIndex("ValueVisuPage");

                    b.ToTable("PropertyInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplate", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1024);

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("GroupOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(8)")
                        .HasDefaultValueSql("1");

                    b.Property<bool>("IsReadonly")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Meta")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(8)")
                        .HasDefaultValueSql("1");

                    b.Property<Guid?>("This2NodeTemplate")
                        .HasDefaultValue(null);

                    b.Property<long>("This2PropertyType")
                        .HasColumnType("bigint(20)");

                    b.Property<Guid?>("This2VisuObjectTemplate")
                        .HasDefaultValue(null);

                    b.HasKey("ObjId");

                    b.HasIndex("This2NodeTemplate");

                    b.HasIndex("This2PropertyType");

                    b.HasIndex("This2VisuObjectTemplate");

                    b.ToTable("PropertyTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplateConstraint", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ConstraintLevel")
                        .HasColumnType("int(20)");

                    b.Property<long>("ConstraintType")
                        .HasColumnType("int(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("This2PropertyTemplate");

                    b.HasKey("ObjId");

                    b.HasIndex("This2PropertyTemplate");

                    b.ToTable("PropertyTemplateConstraints");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplateConstraintData", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ConditionType")
                        .HasColumnType("int(20)");

                    b.Property<double>("Factor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(1.0);

                    b.Property<double>("Offset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.0);

                    b.Property<string>("PropertyKey")
                        .HasColumnType("varchar(1024)");

                    b.Property<Guid>("This2PropertyTemplateConstraint");

                    b.HasKey("ObjId");

                    b.HasIndex("This2PropertyTemplateConstraint");

                    b.ToTable("PropertyTemplateConstraintData");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyType", b =>
                {
                    b.Property<long>("Type")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Meta")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("Type");

                    b.ToTable("PropertyTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInstance", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid?>("This2AreaInstance");

                    b.Property<Guid?>("This2CategoryInstance");

                    b.Property<Guid>("This2RulePage");

                    b.Property<Guid>("This2RuleTemplate");

                    b.Property<Guid?>("This2UserGroup");

                    b.Property<bool>("UseInVisu")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.HasKey("ObjId");

                    b.HasIndex("This2AreaInstance");

                    b.HasIndex("This2CategoryInstance");

                    b.HasIndex("This2RulePage");

                    b.HasIndex("This2RuleTemplate");

                    b.HasIndex("This2UserGroup");

                    b.ToTable("RuleInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInterfaceDirection", b =>
                {
                    b.Property<long>("ObjId")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("RuleInterfaceDirections");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInterfaceInstance", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<Guid>("This2RuleInstance");

                    b.Property<Guid>("This2RuleInterfaceTemplate");

                    b.Property<double?>("ValueDouble");

                    b.Property<long?>("ValueInteger");

                    b.Property<string>("ValueString");

                    b.HasKey("ObjId");

                    b.HasIndex("This2RuleInstance");

                    b.HasIndex("This2RuleInterfaceTemplate");

                    b.ToTable("RuleInterfaceInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInterfaceTemplate", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsLinkableParameter");

                    b.Property<int>("MaxLinks")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("ParameterDataType")
                        .HasColumnType("int(11)");

                    b.Property<int>("SortOrder");

                    b.Property<long>("This2RuleInterfaceDirection")
                        .HasColumnType("bigint(20)");

                    b.Property<Guid>("This2RuleTemplate");

                    b.HasKey("ObjId");

                    b.HasIndex("This2RuleInterfaceDirection");

                    b.HasIndex("This2RuleTemplate");

                    b.ToTable("RuleInterfaceTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RulePage", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<long>("This2RulePageType")
                        .HasColumnType("bigint(20)");

                    b.HasKey("ObjId");

                    b.HasIndex("This2RulePageType");

                    b.ToTable("RulePages");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RulePageType", b =>
                {
                    b.Property<long>("ObjId")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("RulePageTypes");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleTemplate", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<float>("Height");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<Guid>("This2DefaultMobileVisuTemplate")
                        .HasDefaultValue(new Guid("16780dfd-887a-4a0a-9b2a-4d62ccc32c93"));

                    b.Property<float>("Width");

                    b.HasKey("ObjId");

                    b.HasIndex("This2DefaultMobileVisuTemplate");

                    b.ToTable("RuleTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Setting", b =>
                {
                    b.Property<long>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Group")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1024)")
                        .HasDefaultValue("System");

                    b.Property<bool>("IsReadonly");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int>("Order");

                    b.Property<long>("Type")
                        .HasColumnType("int");

                    b.Property<double?>("ValueDouble")
                        .HasColumnType("double");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.Property<string>("ValueKey")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("ValueText")
                        .HasColumnType("text");

                    b.HasKey("ObjId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VersionInformation", b =>
                {
                    b.Property<long>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DriverGuid")
                        .HasMaxLength(36);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(1024)")
                        .HasMaxLength(1024);

                    b.Property<Guid>("RuleGuid")
                        .HasMaxLength(36);

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("VersionInformations");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuObjectInstance", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<float>("Height");

                    b.Property<bool>("IsFavorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Rating");

                    b.Property<Guid?>("This2UserGroup");

                    b.Property<Guid>("This2VisuObjectTemplate");

                    b.Property<Guid>("This2VisuPage");

                    b.Property<float>("Width");

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.HasKey("ObjId");

                    b.HasIndex("This2UserGroup");

                    b.HasIndex("This2VisuObjectTemplate");

                    b.HasIndex("This2VisuPage");

                    b.ToTable("VisuObjectInstances");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuObjectTemplate", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<float>("Height");

                    b.Property<bool>("IsVisibleForUser")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<long>("This2VisuPageType")
                        .HasColumnType("bigint(20)");

                    b.Property<float>("Width");

                    b.HasKey("ObjId");

                    b.HasIndex("This2VisuPageType");

                    b.ToTable("VisuObjectTemplates");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuPage", b =>
                {
                    b.Property<Guid>("ObjId");

                    b.Property<bool>("DefaultPage")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(4.0);

                    b.Property<bool>("IsFavorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<int>("Rating");

                    b.Property<Guid?>("This2UserGroup");

                    b.Property<long>("This2VisuPageType")
                        .HasColumnType("bigint(20)");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(6.0);

                    b.HasKey("ObjId");

                    b.HasIndex("ObjId");

                    b.HasIndex("This2UserGroup");

                    b.HasIndex("This2VisuPageType")
                        .HasName("This2VisuPageType");

                    b.ToTable("VisuPages");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuPageType", b =>
                {
                    b.Property<long>("ObjId")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.HasKey("ObjId");

                    b.ToTable("VisuPageTypes");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.Priviledge", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ObjId");

                    b.ToTable("Priviledges");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.Priviledge2Role", b =>
                {
                    b.Property<Guid>("This2Role");

                    b.Property<Guid>("This2Priviledge");

                    b.HasKey("This2Role");

                    b.HasAlternateKey("This2Priviledge");

                    b.ToTable("Priviledge2Roles");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.Role", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<bool>("IsDeleteable")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ObjId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.User", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ObjId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.User2Group", b =>
                {
                    b.Property<Guid>("This2User");

                    b.Property<Guid>("This2UserGroup");

                    b.HasKey("This2User", "This2UserGroup");

                    b.HasIndex("This2UserGroup");

                    b.ToTable("User2Groups");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.User2Role", b =>
                {
                    b.Property<Guid>("This2User");

                    b.Property<Guid>("This2Role");

                    b.HasKey("This2User", "This2Role");

                    b.HasIndex("This2Role");

                    b.ToTable("User2Roles");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.UserGroup", b =>
                {
                    b.Property<Guid>("ObjId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("ObjId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.UserGroup2Role", b =>
                {
                    b.Property<Guid>("This2UserGroup");

                    b.Property<Guid>("This2Role");

                    b.HasKey("This2UserGroup", "This2Role");

                    b.HasIndex("This2Role");

                    b.ToTable("UserGroup2Roles");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Areas.AreaInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaTemplate", "This2AreaTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2AreaTemplate")
                        .HasConstraintName("FK_AreaInstance_This2AreaTemplateNavigation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaInstance", "This2ParentNavigation")
                        .WithMany("InverseThis2ParentNavigation")
                        .HasForeignKey("This2Parent")
                        .HasConstraintName("FK_AreaInstance_This2ParentNavigation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("NodeInstance_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Areas.AreaTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaType", "NeedsThis2AreaTypeNavigation")
                        .WithMany()
                        .HasForeignKey("NeedsThis2AreaType")
                        .HasConstraintName("FK_AreaTemplate_NeedsThis2AreaTypeNavigation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaType", "ProvidesThis2AreayTypeNavigation")
                        .WithMany()
                        .HasForeignKey("ProvidesThis2AreayType")
                        .HasConstraintName("FK_AreaTemplate_ProvidesThis2AreayTypeNavigation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaType", "This2AreaTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2AreaType")
                        .HasConstraintName("FK_AreaTemplate_AreaType")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.BoardInterface", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.BoardType", "This2BoardTypeNavigation")
                        .WithMany("BoardInterface")
                        .HasForeignKey("This2BoardType")
                        .HasConstraintName("BoardInterface_ibfk_1");

                    b.HasOne("Automatica.Core.EF.Models.InterfaceType", "This2InterfaceTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2InterfaceType")
                        .HasConstraintName("BoardInterface_ibfk_2");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Categories.CategoryInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.Categories.CategoryGroup", "This2CategoryGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2CategoryGroup")
                        .HasConstraintName("FK_CategoryInstance_This2CategoryGroupNavigation")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("NodeInstance_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.Link", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.NodeInstance2RulePage", "This2NodeInstance2RulePageInputNavigation")
                        .WithMany()
                        .HasForeignKey("This2NodeInstance2RulePageInput")
                        .HasConstraintName("Link_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.NodeInstance2RulePage", "This2NodeInstance2RulePageOutputNavigation")
                        .WithMany()
                        .HasForeignKey("This2NodeInstance2RulePageOutput")
                        .HasConstraintName("Link_ibfk_5")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.RuleInterfaceInstance", "This2RuleInterfaceInstanceInputNavigation")
                        .WithMany()
                        .HasForeignKey("This2RuleInterfaceInstanceInput")
                        .HasConstraintName("Link_ibfk_3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.RuleInterfaceInstance", "This2RuleInterfaceInstanceOutputNavigation")
                        .WithMany()
                        .HasForeignKey("This2RuleInterfaceInstanceOutput")
                        .HasConstraintName("Link_ibfk_4")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.RulePage", "This2RulePageNavigation")
                        .WithMany("Link")
                        .HasForeignKey("This2RulePage")
                        .HasConstraintName("Link_ibfk_1");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaInstance", "This2AreaInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("This2AreaInstance")
                        .HasConstraintName("NodeInstance_This2AreaInstance");

                    b.HasOne("Automatica.Core.EF.Models.Categories.CategoryInstance", "This2CategoryInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("This2CategoryInstance")
                        .HasConstraintName("NodeInstance_This2CategoryInstance");

                    b.HasOne("Automatica.Core.EF.Models.NodeTemplate", "This2NodeTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2NodeTemplate")
                        .HasConstraintName("NodeInstance_ibfk_2");

                    b.HasOne("Automatica.Core.EF.Models.NodeInstance", "This2ParentNodeInstanceNavigation")
                        .WithMany("InverseThis2ParentNodeInstanceNavigation")
                        .HasForeignKey("This2ParentNodeInstance")
                        .HasConstraintName("NodeInstance_ibfk_3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("NodeInstance_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeInstance2RulePage", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.NodeInstance", "This2NodeInstanceNavigation")
                        .WithMany("NodeInstance2RulePage")
                        .HasForeignKey("This2NodeInstance")
                        .HasConstraintName("NodeInstance2RulePage_ibfk_2");

                    b.HasOne("Automatica.Core.EF.Models.RulePage", "This2RulePageNavigation")
                        .WithMany("NodeInstance2RulePage")
                        .HasForeignKey("This2RulePage")
                        .HasConstraintName("NodeInstance2RulePage_ibfk_1");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.NodeTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.InterfaceType", "NeedsInterface2InterfacesTypeNavigation")
                        .WithMany()
                        .HasForeignKey("NeedsInterface2InterfacesType")
                        .HasConstraintName("NodeTemplate_ibfk_1");

                    b.HasOne("Automatica.Core.EF.Models.InterfaceType", "ProvidesInterface2InterfaceTypeNavigation")
                        .WithMany()
                        .HasForeignKey("ProvidesInterface2InterfaceType")
                        .HasConstraintName("NodeTemplate_ibfk_2");

                    b.HasOne("Automatica.Core.EF.Models.VisuObjectTemplate", "THis2DefaultMobileVisuTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2DefaultMobileVisuTemplate")
                        .HasConstraintName("NodeTemplate_DefaultVisuMobileTemplate")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Automatica.Core.EF.Models.NodeDataType", "This2NodeDataTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2NodeDataType")
                        .HasConstraintName("NodeTemplate_ibfk_3");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.NodeInstance", "This2NodeInstanceNavigation")
                        .WithMany("PropertyInstance")
                        .HasForeignKey("This2NodeInstance")
                        .HasConstraintName("PropertyInstance_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.PropertyTemplate", "This2PropertyTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2PropertyTemplate")
                        .HasConstraintName("PropertyInstance_ibfk_1");

                    b.HasOne("Automatica.Core.EF.Models.VisuObjectInstance", "This2VisuObjectInstanceNavigation")
                        .WithMany("PropertyInstance")
                        .HasForeignKey("This2VisuObjectInstance")
                        .HasConstraintName("PropertyInstance_VisuObjectInstance_ibfk_3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaInstance", "ValueAreaInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("ValueAreaInstance")
                        .HasConstraintName("PropertyInstance_AreaInstance_ValueAreaInstance")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.Categories.CategoryInstance", "ValueCategoryInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("ValueCategoryInstance")
                        .HasConstraintName("PropertyInstance_CategoryInstance_ValueCategoryInstance")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.NodeInstance", "ValueNodeInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("ValueNodeInstance")
                        .HasConstraintName("PropertyInstance_NodeInstance_ValueNodeInstance")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Automatica.Core.EF.Models.RulePage", "ValueRulePageNavigation")
                        .WithMany()
                        .HasForeignKey("ValueRulePage")
                        .HasConstraintName("PropertyInstance_RulePage_ValueRulePage")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Automatica.Core.EF.Models.VisuPage", "ValueVisuPageNavigation")
                        .WithMany()
                        .HasForeignKey("ValueVisuPage")
                        .HasConstraintName("PropertyInstance_VisuPage_ValueVisuPage")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.NodeTemplate", "This2NodeTemplateNavigation")
                        .WithMany("PropertyTemplate")
                        .HasForeignKey("This2NodeTemplate")
                        .HasConstraintName("PropertyTemplate_ibfk_2");

                    b.HasOne("Automatica.Core.EF.Models.PropertyType", "This2PropertyTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2PropertyType")
                        .HasConstraintName("PropertyTemplate_ibfk_1");

                    b.HasOne("Automatica.Core.EF.Models.VisuObjectTemplate", "This2VisuObjectTemplateNavigation")
                        .WithMany("PropertyTemplate")
                        .HasForeignKey("This2VisuObjectTemplate")
                        .HasConstraintName("PropertyTemplate_ibfk_3");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplateConstraint", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.PropertyTemplate", "This2PropertyTemplateNavigation")
                        .WithMany("Constraints")
                        .HasForeignKey("This2PropertyTemplate")
                        .HasConstraintName("PropertyTemplateConstraint_PropertyTemplate_Navigation")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.PropertyTemplateConstraintData", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.PropertyTemplateConstraint", "This2PropertyTemplateConstraintNavigation")
                        .WithMany("ConstraintData")
                        .HasForeignKey("This2PropertyTemplateConstraint")
                        .HasConstraintName("This2PropertyTemplateConstraintNavigation_PropertyTemplate_Navigation")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.Areas.AreaInstance", "This2AreaInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("This2AreaInstance")
                        .HasConstraintName("RuleInstance_This2AreaInstance");

                    b.HasOne("Automatica.Core.EF.Models.Categories.CategoryInstance", "This2CategoryInstanceNavigation")
                        .WithMany()
                        .HasForeignKey("This2CategoryInstance")
                        .HasConstraintName("RuleInstance_This2CategoryInstance");

                    b.HasOne("Automatica.Core.EF.Models.RulePage", "This2RulePageNavigation")
                        .WithMany("RuleInstance")
                        .HasForeignKey("This2RulePage")
                        .HasConstraintName("RuleInstance_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.RuleTemplate", "This2RuleTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2RuleTemplate")
                        .HasConstraintName("RuleInstance_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("RuleInstance_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInterfaceInstance", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.RuleInstance", "This2RuleInstanceNavigation")
                        .WithMany("RuleInterfaceInstance")
                        .HasForeignKey("This2RuleInstance")
                        .HasConstraintName("RuleInterfaceInstance_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.RuleInterfaceTemplate", "This2RuleInterfaceTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2RuleInterfaceTemplate")
                        .HasConstraintName("RuleInterfaceInstance_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleInterfaceTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.RuleInterfaceDirection", "This2RuleInterfaceDirectionNavigation")
                        .WithMany()
                        .HasForeignKey("This2RuleInterfaceDirection")
                        .HasConstraintName("RuleInterfaceTemplate_ibfk_2");

                    b.HasOne("Automatica.Core.EF.Models.RuleTemplate", "This2RuleTemplateNavigation")
                        .WithMany("RuleInterfaceTemplate")
                        .HasForeignKey("This2RuleTemplate")
                        .HasConstraintName("RuleInterfaceTemplate_ibfk_1");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RulePage", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.RulePageType", "This2RulePageTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2RulePageType")
                        .HasConstraintName("RulePage_ibfk_1");
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.RuleTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.VisuObjectTemplate", "This2DefaultMobileVisuTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2DefaultMobileVisuTemplate")
                        .HasConstraintName("RuleTemplate_DefaultVisuMobileTemplate")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuObjectInstance", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("VisuObjectInstance_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.VisuObjectTemplate", "This2VisuObjectTemplateNavigation")
                        .WithMany()
                        .HasForeignKey("This2VisuObjectTemplate")
                        .HasConstraintName("VisuObjectInstance_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.VisuPage", "This2VisuPageNavigation")
                        .WithMany("VisuObjectInstances")
                        .HasForeignKey("This2VisuPage")
                        .HasConstraintName("VisuObjectInstance_ibfk_2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuObjectTemplate", b =>
                {
                    b.HasOne("Automatica.Core.EF.Models.VisuPageType", "This2VisuPageTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2VisuPageType")
                        .HasConstraintName("FK_VisuObjectTemplates_VisuPageTypes_VisuPageTypeObjId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Automatica.Core.EF.Models.VisuPage", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany()
                        .HasForeignKey("This2UserGroup")
                        .HasConstraintName("VisuPage_This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.EF.Models.VisuPageType", "This2VisuPageTypeNavigation")
                        .WithMany()
                        .HasForeignKey("This2VisuPageType")
                        .HasConstraintName("VisuPage_ibfk_1")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.Priviledge2Role", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.Priviledge", "This2PriviledgeNavigation")
                        .WithMany("InverseThis2Roles")
                        .HasForeignKey("This2Priviledge")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.Role", "This2RoleNavigation")
                        .WithMany("InverseThis2Priviledges")
                        .HasForeignKey("This2Role")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.User2Group", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.User", "This2UserNavigation")
                        .WithMany("InverseThis2UserGroups")
                        .HasForeignKey("This2User")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany("InverseThis2Users")
                        .HasForeignKey("This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.User2Role", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.Role", "This2RoleNavigation")
                        .WithMany()
                        .HasForeignKey("This2Role")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.User", "This2UserNavigation")
                        .WithMany("InverseThis2Roles")
                        .HasForeignKey("This2User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Automatica.Core.Model.Models.User.UserGroup2Role", b =>
                {
                    b.HasOne("Automatica.Core.Model.Models.User.Role", "This2RoleNavigation")
                        .WithMany()
                        .HasForeignKey("This2Role")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Automatica.Core.Model.Models.User.UserGroup", "This2UserGroupNavigation")
                        .WithMany("InverseThis2Roles")
                        .HasForeignKey("This2UserGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
